"""
OMX Team Utilities — Helper functions for team operations.

Generated by OMX agentic team demo (Worker 1).
"""

import hashlib
import json
import os
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Optional


def is_safe_path(path: str, base_dir: Optional[str] = None) -> bool:
    """
    Verify that a path is safe and stays within the base directory.
    Defaults to current working directory if base_dir is not provided.
    Uses realpath to resolve symlinks and prevent traversal attacks.
    """
    if base_dir is None:
        base_dir = os.getcwd()

    base_dir = os.path.realpath(base_dir)
    target_path = os.path.realpath(path)

    # Ensure base_dir ends with a separator to avoid partial name matches
    # e.g., /app/project and /app/project-secret
    prefix = os.path.join(base_dir, "")
    return os.path.commonpath([prefix, target_path]) == os.path.commonpath([prefix])


def generate_task_id(prefix: str = "task") -> str:
    """Generate a unique task ID with optional prefix."""
    short_uuid = str(uuid.uuid4())[:8]
    return f"{prefix}-{short_uuid}"


def generate_correlation_id() -> str:
    """
    Generate a VaultWares-style CorrelationId.
    Format: 7-character alphanumeric starting with lowercase 'c'.
    """
    raw = uuid.uuid4().hex[:6]
    return f"c{raw}"


def format_timestamp(epoch: float = None) -> str:
    """Format an epoch timestamp as ISO 8601 UTC string."""
    if epoch is None:
        epoch = time.time()
    dt = datetime.fromtimestamp(epoch, tz=timezone.utc)
    return dt.isoformat()


def format_duration(seconds: float) -> str:
    """Format a duration in seconds to a human-readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    remaining = seconds % 60
    if minutes < 60:
        return f"{minutes}m {remaining:.0f}s"
    hours = int(minutes // 60)
    remaining_min = minutes % 60
    return f"{hours}h {remaining_min}m"


def build_redis_message(
    agent_id: str,
    action: str,
    task: str = "",
    target: str = "",
    **details: Any,
) -> dict:
    """
    Build a standardized Redis message dict.

    Follows the VaultWares ADK message schema:
    {agent, action, task, target, details, timestamp, correlation_id}
    """
    return {
        "agent": agent_id,
        "action": action,
        "task": task,
        "target": target,
        "details": details,
        "timestamp": format_timestamp(),
        "correlation_id": generate_correlation_id(),
    }


def safe_write_file(path: str, content: str, create_dirs: bool = True) -> bool:
    """
    Safely write content to a file with optional directory creation.
    Ensures the path does not escape the current working directory.

    Returns True on success, False on failure.
    """
    if not is_safe_path(path):
        return False

    try:
        abs_path = os.path.abspath(path)
        if create_dirs:
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    except OSError:
        return False


def compute_file_hash(path: str) -> str:
    """Compute SHA-256 hash of a file's contents."""
    sha256 = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()


def json_dumps_safe(obj: Any, indent: int = 2) -> str:
    """JSON serialize with safe defaults (no ASCII escaping, sorted keys)."""
    return json.dumps(obj, indent=indent, ensure_ascii=False, sort_keys=True, default=str)


def is_safe_path(base_dir: str, rel_path: str, follow_symlinks: bool = True) -> bool:
    """
    Check if a relative path is safe to write/read within a base directory.

    Ensures the resolved path stays within base_dir to prevent path traversal.
    """
    # Join and resolve to absolute path
    if follow_symlinks:
        target_path = os.path.realpath(os.path.join(base_dir, rel_path))
    else:
        target_path = os.path.abspath(os.path.join(base_dir, rel_path))

    base_path = os.path.realpath(base_dir)

    # Check if target_path is within base_path
    return os.path.commonpath([base_path, target_path]) == base_path
